com-pas/compas-sct

.github/workflows/reuse.yml
LICENSES/Apache-2.0.txt
README.md

Added REUSE Github Action

---

sct-app/src/main/java/org/lfenergy/compas/sct/app/SclAutomationService.java
sct-app/src/test/java/org.lfenergy.compas.sct.app/SclAutomationServiceTest.java

Signed-off-by: Aliou DIAITE <aliou.diaite@rte-france.com>

[#65] : correcting history for automation service

---

pom.xml
sct-commons/src/main/java/org/lfenergy/compas/sct/commons/dto/DaTypeName.java
sct-commons/src/main/java/org/lfenergy/compas/sct/commons/dto/DataTypeName.java
sct-commons/src/main/java/org/lfenergy/compas/sct/commons/dto/DoTypeName.java
sct-commons/src/main/java/org/lfenergy/compas/sct/commons/dto/LNodeDTO.java
sct-commons/src/main/java/org/lfenergy/compas/sct/commons/dto/ResumedDataTemplate.java
sct-commons/src/main/java/org/lfenergy/compas/sct/commons/scl/SclService.java
sct-commons/src/main/java/org/lfenergy/compas/sct/commons/scl/dtt/DATypeAdapter.java
sct-commons/src/main/java/org/lfenergy/compas/sct/commons/scl/dtt/DOTypeAdapter.java
sct-commons/src/main/java/org/lfenergy/compas/sct/commons/scl/dtt/LNodeTypeAdapter.java
sct-commons/src/main/java/org/lfenergy/compas/sct/commons/scl/ied/AbstractLNAdapter.java
sct-commons/src/main/java/org/lfenergy/compas/sct/commons/scl/ied/LDeviceAdapter.java
sct-commons/src/test/java/org/lfenergy/compas/sct/commons/dto/DaTypeNameTest.java
sct-commons/src/test/java/org/lfenergy/compas/sct/commons/dto/DoTypeNameTest.java
sct-commons/src/test/java/org/lfenergy/compas/sct/commons/dto/LNodeDTOTest.java
sct-commons/src/test/java/org/lfenergy/compas/sct/commons/dto/ResumedDataTemplateTest.java
sct-commons/src/test/java/org/lfenergy/compas/sct/commons/scl/SclServiceTest.java
sct-commons/src/test/java/org/lfenergy/compas/sct/commons/scl/dtt/DATypeAdapterTest.java
sct-commons/src/test/java/org/lfenergy/compas/sct/commons/scl/dtt/DOTypeAdapterTest.java
sct-commons/src/test/java/org/lfenergy/compas/sct/commons/scl/ied/LN0AdapterTest.java
sct-commons/src/test/java/org/lfenergy/compas/sct/commons/testhelpers/DataTypeUtils.java
sct-commons/src/test/java/org/lfenergy/compas/sct/commons/testhelpers/MarshallerWrapper.java
sct-commons/src/test/resources/scl-srv-import-ieds/ied_test_aggregate_DAI.xml
sct-commons/src/test/resources/scl-srv-import-ieds/ied_test_updatable_DAI.xml

[#70] : all updatable DA should be returned

---

sct-commons/pom.xml
sct-commons/src/main/java/org/lfenergy/compas/sct/commons/Utils.java
sct-commons/src/main/java/org/lfenergy/compas/sct/commons/dto/ControlBlock.java
sct-commons/src/main/java/org/lfenergy/compas/sct/commons/dto/DaTypeName.java
sct-commons/src/main/java/org/lfenergy/compas/sct/commons/dto/FCDAInfo.java
sct-commons/src/main/java/org/lfenergy/compas/sct/commons/dto/GooseControlBlock.java
sct-commons/src/main/java/org/lfenergy/compas/sct/commons/dto/SMVControlBlock.java
sct-commons/src/main/java/org/lfenergy/compas/sct/commons/scl/SclService.java
sct-commons/src/main/java/org/lfenergy/compas/sct/commons/scl/dtt/AbstractDataAttributeAdapter.java
sct-commons/src/main/java/org/lfenergy/compas/sct/commons/scl/ied/AbstractDAIAdapter.java
sct-commons/src/main/java/org/lfenergy/compas/sct/commons/scl/ied/AbstractLNAdapter.java
sct-commons/src/main/java/org/lfenergy/compas/sct/commons/scl/ied/LN0Adapter.java
sct-commons/src/main/resources/binding_configuration.xjb
sct-commons/src/test/java/org/lfenergy/compas/sct/commons/UtilsTest.java
sct-commons/src/test/java/org/lfenergy/compas/sct/commons/scl/SclServiceTest.java
sct-commons/src/test/java/org/lfenergy/compas/sct/commons/scl/ied/DOIAdapterTest.java
sct-commons/src/test/resources/scl-remove-controlBlocks-dataSet-extRefSrc/scl-with-control-blocks.xml

[#74] : delete all Control Blocks and Dataset and all ExtRef @srcXXX attributes

---

sct-app/src/test/java/org.lfenergy.compas.sct.app/SclAutomationServiceTest.java
sct-commons/src/main/java/org/lfenergy/compas/sct/commons/scl/SclService.java
sct-commons/src/test/java/org/lfenergy/compas/sct/commons/scl/SclRootAdapterTest.java
sct-commons/src/test/java/org/lfenergy/compas/sct/commons/scl/SclServiceTest.java
sct-commons/src/test/java/org/lfenergy/compas/sct/commons/scl/ied/IEDAdapterTest.java
sct-commons/src/test/java/org/lfenergy/compas/sct/commons/testhelpers/SclTestMarshaller.java

Signed-off-by: Samir Romdhani <samir.romdhani@rte-france.com>

fix error marshalling SCL after automatic scd creation call

---

.github/workflows/javadoc.yml

Signed-off-by: Samir Romdhani <samir.romdhani@rte-france.com>

automated javadocs updates

---

sct-commons/src/main/java/org/lfenergy/compas/sct/commons/scl/SubstationService.java
sct-commons/src/main/java/org/lfenergy/compas/sct/commons/scl/sstation/FunctionAdapter.java
sct-commons/src/test/java/org/lfenergy/compas/sct/commons/scl/SubstationServiceTest.java
sct-commons/src/test/java/org/lfenergy/compas/sct/commons/scl/sstation/FunctionAdapterTest.java

[#153] : remove service updateLNodeIEDNames

---

docs/examples/example-app/pom.xml
docs/examples/example-app/src/main/java/org/lfenergy/compas/sct/examples/SctAppExample.java
docs/examples/example-app/src/test/java/org/lfenergy/compas/sct/examples/SctAppExampleTest.java

Update junit version
Signed-off-by: Samir Romdhani <samir.romdhani@rte-france.com>

update junit version

---

pom.xml
sct-app/pom.xml
sct-commons/pom.xml
sct-data/pom.xml

[#170] Generate source artefact for each module

---

sct-app/src/main/java/org/lfenergy/compas/sct/app/SclAutomationService.java
sct-commons/src/main/java/org/lfenergy/compas/sct/commons/dto/DataTypeName.java
sct-commons/src/main/java/org/lfenergy/compas/sct/commons/scl/PrivateService.java
sct-commons/src/main/java/org/lfenergy/compas/sct/commons/scl/SubstationService.java
sct-commons/src/main/java/org/lfenergy/compas/sct/commons/scl/dtt/DATypeAdapter.java
sct-commons/src/main/java/org/lfenergy/compas/sct/commons/scl/dtt/DOTypeAdapter.java
sct-commons/src/main/java/org/lfenergy/compas/sct/commons/scl/ied/IEDAdapter.java
sct-commons/src/main/java/org/lfenergy/compas/sct/commons/scl/ied/LDeviceAdapter.java
sct-commons/src/main/java/org/lfenergy/compas/sct/commons/util/Utils.java
sct-commons/src/test/java/org/lfenergy/compas/sct/commons/dto/LDeviceDTOTest.java
sct-commons/src/test/java/org/lfenergy/compas/sct/commons/scl/SclRootAdapterTest.java
sct-commons/src/test/java/org/lfenergy/compas/sct/commons/testhelpers/marshaller/MarshallerWrapper.java

Suppress useless @Slf4J decorators
Signed-off-by: gleizesDor <115622893+gleizesDor@users.noreply.github.com>

feat: Suppress useless Slf4J

---

sct-commons/src/main/java/org/lfenergy/compas/sct/commons/dto/IedDTO.java
sct-commons/src/main/java/org/lfenergy/compas/sct/commons/dto/SclReport.java
sct-commons/src/main/java/org/lfenergy/compas/sct/commons/scl/ExtRefService.java
sct-commons/src/main/java/org/lfenergy/compas/sct/commons/scl/SclRootAdapter.java
sct-commons/src/main/java/org/lfenergy/compas/sct/commons/scl/SclService.java
sct-commons/src/main/java/org/lfenergy/compas/sct/commons/scl/ied/AbstractLNAdapter.java
sct-commons/src/main/java/org/lfenergy/compas/sct/commons/scl/ied/IEDAdapter.java
sct-commons/src/main/java/org/lfenergy/compas/sct/commons/scl/ied/InputsAdapter.java
sct-commons/src/main/java/org/lfenergy/compas/sct/commons/scl/ied/LDeviceAdapter.java
sct-commons/src/main/java/org/lfenergy/compas/sct/commons/scl/ied/LN0Adapter.java
sct-commons/src/main/java/org/lfenergy/compas/sct/commons/util/Utils.java
sct-commons/src/test/java/org/lfenergy/compas/sct/commons/scl/ExtRefServiceTest.java
sct-commons/src/test/java/org/lfenergy/compas/sct/commons/scl/SclServiceTest.java
sct-commons/src/test/java/org/lfenergy/compas/sct/commons/scl/ied/IEDAdapterTest.java
sct-commons/src/test/java/org/lfenergy/compas/sct/commons/scl/ied/InputsAdapterTest.java
sct-commons/src/test/java/org/lfenergy/compas/sct/commons/scl/ied/LN0AdapterTest.java
sct-commons/src/test/java/org/lfenergy/compas/sct/commons/util/UtilsTest.java
sct-commons/src/test/resources/scd-extref-iedname/scd_set_extref_iedname_success.xml
sct-commons/src/test/resources/scd-extref-iedname/scd_set_extref_iedname_with_errors.xml

[#77] - RSR-369 - set ExtRef iedName part 1

---

sct-commons/src/main/java/org/lfenergy/compas/sct/commons/dto/ExtRefBindingInfo.java
sct-commons/src/main/java/org/lfenergy/compas/sct/commons/scl/SclService.java
sct-commons/src/test/java/org/lfenergy/compas/sct/commons/dto/DTO.java
sct-commons/src/test/java/org/lfenergy/compas/sct/commons/dto/ExtRefBindingInfoTest.java
sct-commons/src/test/java/org/lfenergy/compas/sct/commons/dto/ExtRefInfoTest.java
sct-commons/src/test/java/org/lfenergy/compas/sct/commons/scl/SclServiceTest.java
sct-commons/src/test/java/org/lfenergy/compas/sct/commons/scl/ied/LNAdapterTest.java

Added Comparable functionality to ExtRefBindingInfo to allow sorting result list.
Added some unit tests.
Signed-off-by: SaintierFr <99645240+SaintierFr@users.noreply.github.com>

feat(#176): Alphabetically order possible source of ExtRef binding

---

sct-commons/src/main/java/org/lfenergy/compas/sct/commons/scl/ied/InputsAdapter.java
sct-commons/src/test/java/org/lfenergy/compas/sct/commons/scl/ExtRefServiceTest.java
sct-commons/src/test/resources/scd-extref-iedname/scd_set_extref_iedname_with_extref_errors.xml

fix(78): RSR-437 - add check of source LDevice status

---

.github/workflows/automate_javadoc.yml
.github/workflows/release-project.yml
.github/workflows/reuse.yml
.github/workflows/sonarcloud-analysis.yml
pom.xml
sct-app/pom.xml
sct-commons/pom.xml

Signed-off-by: Aliou DIAITE <aliou.diaite@rte-france.com>

feat(125): upgrade to java 17

---

sct-commons/src/main/java/org/lfenergy/compas/sct/commons/dto/DataTypeName.java

Signed-off-by: gleizesDor <115622893+gleizesDor@users.noreply.github.com>

feat: branche de test de develop

---

sct-commons/src/main/java/org/lfenergy/compas/sct/commons/scl/ied/InputsAdapter.java
sct-commons/src/test/java/org/lfenergy/compas/sct/commons/scl/ied/InputsAdapterForDemoTest.java
sct-commons/src/test/resources/scd-extref-create-dataset-and-controlblocks/scd_create_dataset_and_controlblocks_success.xml

feat(83): RSR-389 - ignore INACTIVE CompasFlow when creating Dataset

---

sct-commons/src/main/java/org/lfenergy/compas/sct/commons/dto/DataSetInfo.java
sct-commons/src/main/java/org/lfenergy/compas/sct/commons/dto/ExtRefInfo.java
sct-commons/src/main/java/org/lfenergy/compas/sct/commons/scl/SclService.java
sct-commons/src/main/java/org/lfenergy/compas/sct/commons/scl/ied/AbstractLNAdapter.java
sct-commons/src/test/java/org/lfenergy/compas/sct/commons/dto/DataSetInfoTest.java
sct-commons/src/test/java/org/lfenergy/compas/sct/commons/dto/ExtRefInfoTest.java
sct-commons/src/test/java/org/lfenergy/compas/sct/commons/scl/SclServiceTest.java
sct-commons/src/test/java/org/lfenergy/compas/sct/commons/scl/ied/LN0AdapterTest.java
sct-commons/src/test/java/org/lfenergy/compas/sct/commons/scl/ied/LNAdapterTest.java
sct-commons/src/test/resources/scd-extref-cb/scd_get_cbs_test.xml

Signed-off-by: Aliou DIAITE <aliou.diaite@rte-france.com>
Signed-off-by: SABATIER Philippe Ext <philippe.sabatier@rte-france.com>

fix(#185): fix bug update extref cb

---

sct-commons/src/main/java/org/lfenergy/compas/sct/commons/scl/ied/InputsAdapter.java
sct-commons/src/test/java/org/lfenergy/compas/sct/commons/scl/ExtRefServiceTest.java
sct-commons/src/test/java/org/lfenergy/compas/sct/commons/scl/ied/InputsAdapterTest.java
sct-commons/src/test/java/org/lfenergy/compas/sct/commons/testhelpers/SclHelper.java

feat(86): RSR-435 - set extRef.srcXXX attribute after creating controlBlocks

---

.github/dependabot.yml
.github/workflows/automate_projects.yml
.github/workflows/build-project.yml
.github/workflows/release-project.yml
.github/workflows/reuse.yml
.github/workflows/sonarcloud-analysis.yml

Update Github workflows like used in other CoMPAS projects
Signed-off-by: SaintierFr <99645240+SaintierFr@users.noreply.github.com>

feat(119): Update Github workflows

---

sct-commons/src/main/java/org/lfenergy/compas/sct/commons/dto/LDEPFSettingData.java
sct-commons/src/main/java/org/lfenergy/compas/sct/commons/scl/ExtRefService.java
sct-commons/src/main/java/org/lfenergy/compas/sct/commons/scl/ied/DOIAdapter.java
sct-commons/src/main/java/org/lfenergy/compas/sct/commons/scl/ied/IEDAdapter.java
sct-commons/src/main/java/org/lfenergy/compas/sct/commons/scl/ied/LDeviceAdapter.java
sct-commons/src/main/java/org/lfenergy/compas/sct/commons/util/CommonConstants.java
sct-commons/src/test/java/org/lfenergy/compas/sct/commons/scl/ExtRefServiceTest.java
sct-commons/src/test/java/org/lfenergy/compas/sct/commons/scl/ied/DOIAdapterTest.java
sct-commons/src/test/java/org/lfenergy/compas/sct/commons/scl/ied/IEDAdapterTest.java
sct-commons/src/test/java/org/lfenergy/compas/sct/commons/scl/ied/LDeviceAdapterTest.java
sct-commons/src/test/java/org/lfenergy/compas/sct/commons/scl/ied/LN0AdapterTest.java
sct-commons/src/test/resources/scd-ldepf/scd_ldepf_dataTypeTemplateValid.xml
sct-commons/src/test/resources/scd-ldepf/scd_ldepf_extref_with_BCU_BPU.xml
sct-commons/src/test/resources/scd-ldepf/scd_ldepf_iedSources_in_different_bay.xml
sct-commons/src/test/resources/scd-ldepf/scd_ldepf_manyIedSources_in_same_bay.xml

Rebase should be done after merging #277 into develop
Issue #256

Feat/256 update do from setting file values : last stage

---

pom.xml

Private compas:Bay@UUID is required

update compas-core version close com-pas/compas-sct#286

---

sct-commons/pom.xml
sct-commons/src/main/java/org/lfenergy/compas/scl2007b4/model/package-info.java
sct-commons/src/main/java/org/lfenergy/compas/sct/commons/util/PrivateUtils.java
sct-commons/src/main/java/org/lfenergy/compas/sct/commons/util/Utils.java
sct-commons/src/main/resources/binding_configuration.xjb
sct-commons/src/test/java/org/lfenergy/compas/sct/commons/scl/sstation/LNodeAdapterTest.java
sct-commons/src/test/java/org/lfenergy/compas/sct/commons/testhelpers/MarshallerWrapper.java
sct-commons/src/test/java/org/lfenergy/compas/sct/commons/util/PrivateUtilsTest.java

- Passage de javax.* à jakarta.*
BREAKING CHANGE: Passage de javax.* à jakarta.*

feat: Upgrade JAXB version - moving javax package to jakarta, close #319

---

sct-commons/src/test/java/org/lfenergy/compas/sct/commons/LNodeStatusServiceTest.java
sct-commons/src/test/resources/scl-lnodestatus/lnodestatus.scd

Reverts com-pas/compas-sct#450

Revert "fix(#449): fix test in LNodeStatusServiceTest"

---

sct-app/src/test/java/org.lfenergy.compas.sct.app/SclAutomationServiceIntegrationTest.java
sct-commons/src/main/java/org/lfenergy/compas/sct/commons/ExtRefReaderService.java
sct-commons/src/main/java/org/lfenergy/compas/sct/commons/SclService.java
sct-commons/src/main/java/org/lfenergy/compas/sct/commons/api/SclEditor.java
sct-commons/src/main/java/org/lfenergy/compas/sct/commons/dto/DataAttributeRef.java
sct-commons/src/main/java/org/lfenergy/compas/sct/commons/scl/ied/IEDAdapter.java
sct-commons/src/main/java/org/lfenergy/compas/sct/commons/scl/ldevice/LDeviceAdapter.java
sct-commons/src/main/java/org/lfenergy/compas/sct/commons/util/CommonConstants.java
sct-commons/src/main/java/org/lfenergy/compas/sct/commons/util/Utils.java
sct-commons/src/test/java/org/lfenergy/compas/sct/commons/ExtRefEditorServiceTest.java
sct-commons/src/test/java/org/lfenergy/compas/sct/commons/SclServiceTest.java
sct-commons/src/test/java/org/lfenergy/compas/sct/commons/scl/ied/IEDAdapterTest.java
sct-commons/src/test/java/org/lfenergy/compas/sct/commons/scl/ldevice/LDeviceAdapterTest.java
sct-commons/src/test/java/org/lfenergy/compas/sct/commons/testhelpers/SclHelper.java
sct-commons/src/test/java/org/lfenergy/compas/sct/commons/util/UtilsTest.java
sct-commons/src/test/resources/monitoring_lns/scd_monitoring_lsvs_lgos_with_privates.xml

https://github.com/com-pas/compas-sct/issues/487

fix copySclElement - refactor manage monitoring lns (LGOS, LSVS), fixes #487

---

sct-commons/src/main/java/org/lfenergy/compas/sct/commons/ExtRefEditorService.java
sct-commons/src/test/java/org/lfenergy/compas/sct/commons/ExtRefEditorServiceTest.java
sct-commons/src/test/resources/scd-ldepf/scd_ldepf_dataTypeTemplateValid.xml
sct-commons/src/test/resources/scd-ldepf/scd_ldepf_manyIedSources_in_same_bay.xml
sct-commons/src/test/resources/scd-ldepf/scd_ldepf_processing_external_bind.xml
sct-commons/src/test/resources/scd-ldepf/scd_ldepf_processing_internal_bind.xml
sct-commons/src/test/resources/scd-ldepf/scd_ldepf_processing_when_status_ln0_off.xml

feat: added aRBDR for Analog Channel instead of aRADR, closes #512, RSR-1242

---

sct-commons/src/main/java/org/lfenergy/compas/sct/commons/ExtRefEditorService.java
sct-commons/src/test/java/org/lfenergy/compas/sct/commons/ExtRefEditorServiceTest.java
sct-commons/src/test/java/org/lfenergy/compas/sct/commons/testhelpers/SclHelper.java
sct-commons/src/test/resources/scd-ldepf/scd_ldepf_postProcessing_when_ln0_off.xml

feat: LDEPF post configuration, Inref should not be configured when inactive, closes #510, RSR-1240
